language: node_js
node_js:
- 10.13.0
env:
  global:
  - USER=root
  - IP=132.232.119.172
before_install:
- openssl aes-256-cbc -K $encrypted_77250ec3da23_key -iv $encrypted_77250ec3da23_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
cache:
  directories:
  - node_modules
install:
- npm install
notifications:
  email:
    recipients:
    - ovenzeze@qq.com
    on_success: always
    on_failure: always
script:
- hexo g
after_success:
- chmod 600 ~/.ssh/id_rsa
- scp -r ./public  $USER@$IP:/root/github/ovenzeze.github.io
addons:
  ssh_known_hosts: 132.232.119.172
