language: node_js
node_js:
- 10.13.0
env:
  global:
  - USER=root
  - IP=111.231.253.254
before_install:
  - openssl aes-256-cbc -K $encrypted_bebbbd09f6b0_key -iv $encrypted_bebbbd09f6b0_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
cache:
  directories:
  - node_modules
install:
- npm install
notifications:
  email:
    recipients:
    - ovenzeze@qq.com
    on_success: always
    on_failure: always
script:
- hexo g

after_success:
- chmod 600 ~/.ssh/id_rsa
- scp public/ -r $USER@$IP:/root/server/clay-blog/ovenzeze.github.io/public
addons:
  ssh_known_hosts: 111.231.253.254
