language: node_js
node_js:
- 10.13.0
env:
  global:
  - USER=root
  - IP=111.231.253.254
cache:
  directories:
  - node_modules
install:
- npm install
notifications:
  email:
    recipients:
    - ovenzeze@qq.com
    on_success: always
    on_failure: always
script:
- hexo g
- 
after_success:
- chmod 600 ~/.ssh/id_rsa
- scp public/ -r $USER@$IP:/root/server/clay-blog/ovenzeze.github.io/public
addons:
  ssh_known_hosts: 111.231.253.254
